name: Playwright run tests

on: workflow_dispatch

jobs:
    run-e2e-test:
        runs-on: ubuntu-latest
        needs: []
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - uses: microsoft/playwright-github-action@v1
            - name: Install dependencies and run tests
              run: npm ci && npm run install:qa && npm run test:qa
              env:
                  # configure tests with environment variables
                  FFMPEG_PATH: /usr/bin/ffmpeg # for recording video
                  QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts
                  # you can also use GitHub secrets for environment variables
                  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
                  # Valid username and password
                  VALID_USER: ${{ secrets.VALID_USER }}
                  VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
                  # Address to run the test against
                  HOME_URL: ${{ secrets.HOME_URL }}
                  # This is used to bypass duo page.
                  QABOX_USER_CODE: ${{ secrets.QABOX_USER_CODE }}
                  QABOX_EMAIL: ${{ secrets.QABOX_EMAIL }}
                  QABOX_PASSWORD: ${{ secrets.QABOX_PASSWORD }}
                  # The URL APP ID that is used to connect to the backend
                  QABOX_SERVER: ${{ secrets.QABOX_SERVER }}
                  QABOX_APP_ID: ${{ secrets.QABOX_APP_ID }}
                  # Used to tell tests to connect to QA (set to false for auto)
                  QA_SETUP: ${{ secrets.QA_SETUP }}
                  DERIV_COM_URL: ${{ secrets.DERIV_COM_URL }}

            - name: Upload Artifacts
              if: always()
              uses: actions/upload-artifact@master
              with:
                  name: qawolf
                  path: ${{ github.workspace }}/artifacts
